// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package api;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\022\003api\"\033\n\014HelloRequest\022\013\n\003m" +
      "sg\030\001 \001(\t\"-\n\rHelloResponse\022\013\n\003msg\030\001 \001(\t\022\017" +
      "\n\007success\030\002 \001(\010B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_HelloRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_api_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_HelloResponse_descriptor,
        new java.lang.String[] { "Msg", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
