// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package api;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();
}
